spring.datasource.url=jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.mlopfezzkszrcqxwwqqv
spring.datasource.password=9aJ?}3DX-8kF?EB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Tracing
spring.sleuth.enabled=true
spring.zipkin.enabled=true
server.port=8083
